# Generated by Django 4.2.5 on 2023-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_date_alter_photo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
