# Generated by Django 4.2.5 on 2023-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_album_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Owner'),
        ),
    ]
